name: mapita_app
description: "Mapita App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  animate_do: ^4.2.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.2
  gap: ^3.0.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  google_polyline_algorithm: ^3.1.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
